apiVersion: aptify/v1alpha1
kind: Repository
releases:
  - name: bookworm
    origin: Damian Peckett <damian@pecke.tt>
    label: Immutos APT Repository
    suite: bookworm
    components:
      - name: stable
        packages:
          - vendor/immutos/boards/linux-image-*6.1.*.deb
          - vendor/immutos/debco/*.deb
          - vendor/immutos/fsutil/*.deb
          - vendor/immutos/matchstick/*.deb
          - vendor/immutos/oci2erofs/*.deb
          - vendor/immutos/vt100/*.deb
  - name: trixie
    origin: Damian Peckett <damian@pecke.tt>
    label: Immutos APT Repository
    suite: trixie
    components:
      - name: testing
        packages:
          - vendor/immutos/boards/bootloader-immutos-milkv-duo*.deb
          - vendor/immutos/boards/linux-image-*6.11.*.deb
          - vendor/immutos/debco/*.deb
          - vendor/immutos/matchstick/*.deb
          - vendor/immutos/oci2erofs/*.deb