name: Publish APT repository

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: "1"

    steps:
    # There's often quite a bit of clock skew on GitHub Actions.
    - name: Sync system time with NTP
      run: |
        sudo apt update && sudo apt install -y ntpdate
        sudo ntpdate -u time.google.com
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Setup aptify config directory
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        mkdir -p ~/.config/aptify
        umask 077
        echo "$GPG_KEY" > ~/.config/aptify/aptify_private.asc
      
    - name: Install tools
      run: |
        curl -fsL -o /usr/local/bin/aptify https://github.com/dpeckett/aptify/releases/download/v0.8.0/aptify-linux-amd64
        curl -fsL -o /usr/local/bin/vendir https://github.com/carvel-dev/vendir/releases/download/v0.40.2/vendir-linux-amd64
        sudo chmod +x /usr/local/bin/aptify /usr/local/bin/vendir
    
    - name: Download packages
      env:
        VENDIR_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: vendir sync -l

    - name: Rebuild repository
      run: aptify build -c repository.yaml -d ./repo/

    - name: Sync files to server
      env:
        RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'
      run: |
        rsync -avz --delete ./repo/ github-actions@dpeckett.dev:~/immutos-apt/

